apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app  # Match pods with this label
  ports:
  - protocol: TCP
    port: 80       # Port exposed by the service
    targetPort: 80 # Port on the container
  type: ClusterIP  # Service type (e.g., ClusterIP, NodePort, LoadBalancer)
